package com.bomibear.taskmaster.Model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.ArrayList;

@DynamoDBTable(tableName="taskmaster")
public class Task {

    private String id;
    private String title;
    private String description;
    private String status;
    private String assignee;
    private String pic;

    private ArrayList<History> history;

    public Task(){}

    public Task(String title, String description){
        this.title = title;
        this.description = description;
        this.status = "available";
        this.history = new ArrayList<>();
    }

    public Task(String title, String description, String assignee){
        this.title = title;
        this.description = description;
        this.assignee = assignee;
        this.status = "assigned";
        this.history = new ArrayList<>();
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return title;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @DynamoDBAttribute
    public String getAssignee() {
        return assignee;
    }

    @DynamoDBAttribute
    public ArrayList<History> getHistory() {
        return history;
    }

    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }

    public void setHistory(ArrayList<History> history) {
        this.history = history;
    }

    public void addToHistory(History history){ this.history.add(history);}

    @DynamoDBAttribute
    public String getPic() {
        return pic;
    }

    public void setPic(String pic) {
        this.pic = pic;
    }
}
